'use client'

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface StudentReportProps {
  studentName: string
  testTitle: string
  score: number
  maxScore: number
  percentage: number
  grade: string
  questions: Array<{
    question: string
    studentAnswer: string
    correctAnswer: string
    score: number
    maxScore: number
    feedback?: string
  }>
  teacherNotes?: string
  onExport?: () => void
}

export default function StudentReport({
  studentName,
  testTitle,
  score,
  maxScore,
  percentage,
  grade,
  questions,
  teacherNotes,
  onExport
}: StudentReportProps) {
  const generatePDF = () => {
    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.setTextColor(56, 189, 248)
    doc.text('Test Result Report', 105, 20, { align: 'center' })
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Student: ${studentName}`, 20, 40)
    doc.text(`Test: ${testTitle}`, 20, 50)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60)
    
    // Summary
    autoTable(doc, {
      startY: 70,
      head: [['Metric', 'Value']],
      body: [
        ['Score', `${score}/${maxScore}`],
        ['Percentage', `${percentage}%`],
        ['Grade', grade],
        ['Questions', questions.length.toString()]
      ],
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Questions breakdown
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Question', 'Your Answer', 'Correct Answer', 'Score', 'Feedback']],
      body: questions.map((q, i) => [
        `Q${i + 1}: ${q.question.substring(0, 30)}...`,
        q.studentAnswer,
        q.correctAnswer,
        `${q.score}/${q.maxScore}`,
        q.feedback || ''
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
      bodyStyles: { minCellHeight: 10 },
    })
    
    // Teacher notes
    if (teacherNotes) {
      doc.setFontSize(11)
      doc.text('Teacher Notes:', 20, (doc as any).lastAutoTable.finalY + 20)
      doc.setFontSize(10)
      const splitNotes = doc.splitTextToSize(teacherNotes, 170)
      doc.text(splitNotes, 20, (doc as any).lastAutoTable.finalY + 30)
    }
    
    // Footer
    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pages} • Generated by OfflineTests • For personal review only`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      )
    }
    
    doc.save(`Test_Result_${studentName.replace(/\s+/g, '_')}.pdf`)
    onExport?.()
  }

  const getGradeColor = (grade: string) => {
    switch (grade) {
      case 'A': return 'text-green-400'
      case 'B': return 'text-blue-400'
      case 'C': return 'text-yellow-400'
      case 'D': return 'text-orange-400'
      case 'F': return 'text-red-400'
      default: return 'text-gray-400'
    }
  }

  return (
    <div className="bg-surface border border-border rounded-xl p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-xl font-semibold">Your Test Results</h3>
          <p className="text-gray-400 text-sm mt-1">
            {testTitle} • {new Date().toLocaleDateString()}
          </p>
        </div>
        <button
          onClick={generatePDF}
          className="px-4 py-2 bg-accent text-white rounded-lg hover:bg-blue-500 transition-colors flex items-center space-x-2"
        >
          <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"/>
          </svg>
          <span>Save as PDF</span>
        </button>
      </div>
      
      {/* Score Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-accent">{score}/{maxScore}</div>
          <div className="text-sm text-gray-400">Score</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-green-400">{percentage}%</div>
          <div className="text-sm text-gray-400">Percentage</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className={`text-2xl font-bold ${getGradeColor(grade)}`}>{grade}</div>
          <div className="text-sm text-gray-400">Grade</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-purple-400">
            {questions.filter(q => q.score === q.maxScore).length}/{questions.length}
          </div>
          <div className="text-sm text-gray-400">Correct</div>
        </div>
      </div>
      
      {/* Quick Stats */}
      <div className="mb-6">
        <h4 className="font-semibold mb-3">Question Breakdown</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {questions.map((q, i) => (
            <div key={i} className="bg-background border border-border rounded-lg p-4">
              <div className="flex justify-between items-start mb-2">
                <span className="font-medium">Question {i + 1}</span>
                <span className={`px-2 py-1 rounded text-xs ${
                  q.score === q.maxScore 
                    ? 'bg-green-900/30 text-green-400' 
                    : 'bg-yellow-900/30 text-yellow-400'
                }`}>
                  {q.score}/{q.maxScore}
                </span>
              </div>
              <div className="text-sm text-gray-400 line-clamp-2">{q.question}</div>
              {q.feedback && (
                <div className="mt-2 text-xs text-blue-400">{q.feedback}</div>
              )}
            </div>
          ))}
        </div>
      </div>
      
      {teacherNotes && (
        <div className="p-4 bg-background border border-blue-700/30 rounded-lg">
          <h4 className="font-semibold text-blue-400 mb-2">Teacher's Notes</h4>
          <p className="text-sm text-gray-300">{teacherNotes}</p>
        </div>
      )}
      
      <div className="mt-6 pt-4 border-t border-border text-xs text-gray-400">
        <p>• This report is for your personal records only</p>
        <p>• All test data is encrypted and will be automatically deleted</p>
        <p>• Download and save this report for future reference</p>
      </div>
    </div>
  )
}