'use client'

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface TeacherReportProps {
  testTitle: string
  submissions: Array<{
    studentName: string
    score: number
    maxScore: number
    percentage: number
    grade: string
    submittedAt: string
    suspicious: boolean
  }>
  questionStats: Array<{
    questionNumber: number
    averageScore: number
    maxScore: number
    difficulty: string
  }>
  onExport?: () => void
}

export default function TeacherReport({ 
  testTitle, 
  submissions, 
  questionStats,
  onExport 
}: TeacherReportProps) {
  const generatePDF = () => {
    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.setTextColor(56, 189, 248)
    doc.text('Class Performance Report', 105, 20, { align: 'center' })
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Test: ${testTitle}`, 20, 40)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50)
    doc.text(`Students: ${submissions.length}`, 20, 60)
    
    // Summary stats
    const avgScore = submissions.reduce((sum, s) => sum + s.score, 0) / submissions.length
    const avgPercentage = submissions.reduce((sum, s) => sum + s.percentage, 0) / submissions.length
    
    autoTable(doc, {
      startY: 70,
      head: [['Metric', 'Value']],
      body: [
        ['Average Score', `${avgScore.toFixed(1)}/${submissions[0]?.maxScore || 100}`],
        ['Average Percentage', `${avgPercentage.toFixed(1)}%`],
        ['Highest Score', `${Math.max(...submissions.map(s => s.score))}`],
        ['Lowest Score', `${Math.min(...submissions.map(s => s.score))}`],
        ['Suspicious Submissions', submissions.filter(s => s.suspicious).length.toString()]
      ],
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Student scores table
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Student', 'Score', 'Percentage', 'Grade', 'Status']],
      body: submissions.map(s => [
        s.studentName,
        `${s.score}/${s.maxScore}`,
        `${s.percentage}%`,
        s.grade,
        s.suspicious ? '⚠ Review' : '✓ Normal'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Question analysis
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Question', 'Average Score', 'Difficulty']],
      body: questionStats.map(q => [
        `Q${q.questionNumber}`,
        `${q.averageScore.toFixed(1)}/${q.maxScore}`,
        q.difficulty
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Grade distribution
    const gradeDist = submissions.reduce((acc: Record<string, number>, s) => {
      acc[s.grade] = (acc[s.grade] || 0) + 1
      return acc
    }, {})
    
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Grade', 'Students', 'Percentage']],
      body: Object.entries(gradeDist).map(([grade, count]) => [
        grade,
        count.toString(),
        `${((count / submissions.length) * 100).toFixed(1)}%`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Footer
    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pages} • Generated by OfflineTests • Confidential`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      )
    }
    
    doc.save(`Teacher_Report_${testTitle.replace(/\s+/g, '_')}.pdf`)
    onExport?.()
  }

  return (
    <div className="bg-surface border border-border rounded-xl p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-xl font-semibold">Teacher Report</h3>
          <p className="text-gray-400 text-sm mt-1">
            Generate PDF report for {testTitle}
          </p>
        </div>
        <button
          onClick={generatePDF}
          className="px-4 py-2 bg-accent text-white rounded-lg hover:bg-blue-500 transition-colors flex items-center space-x-2"
        >
          <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"/>
          </svg>
          <span>Export PDF</span>
        </button>
      </div>
      
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-accent">{submissions.length}</div>
          <div className="text-sm text-gray-400">Students</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-green-400">
            {((submissions.reduce((sum, s) => sum + s.score, 0) / submissions.length) || 0).toFixed(1)}
          </div>
          <div className="text-sm text-gray-400">Avg Score</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-yellow-400">
            {submissions.filter(s => s.suspicious).length}
          </div>
          <div className="text-sm text-gray-400">Flagged</div>
        </div>
        <div className="bg-background border border-border rounded-lg p-4 text-center">
          <div className="text-2xl font-bold text-purple-400">{questionStats.length}</div>
          <div className="text-sm text-gray-400">Questions</div>
        </div>
      </div>
      
      <div className="text-sm text-gray-400 space-y-1">
        <p>• Report includes student scores, grade distribution, and question analysis</p>
        <p>• All data is encrypted and automatically expires</p>
        <p>• Generated reports are for teacher records only</p>
      </div>
    </div>
  )
}