'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ClassReport {
  testTitle: string
  totalStudents: number
  averageScore: number
  highestScore: number
  lowestScore: number
  submissions: Array<{
    studentName: string
    score: number
    maxScore: number
    percentage: number
    grade: string
    submittedAt: string
    suspicious: boolean
  }>
  questionStats: Array<{
    questionNumber: number
    averageScore: number
    maxScore: number
    difficulty: 'Easy' | 'Medium' | 'Hard'
  }>
}

export default function TeacherReportPage() {
  const params = useParams()
  const router = useRouter()
  const testId = params.testId as string
  
  const [report, setReport] = useState<ClassReport | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchReport = async () => {
      try {
        // Mock data
        const mockReport: ClassReport = {
          testTitle: 'Calculus Midterm',
          totalStudents: 25,
          averageScore: 38.5,
          highestScore: 48,
          lowestScore: 22,
          submissions: [
            { studentName: 'Alice Johnson', score: 48, maxScore: 50, percentage: 96, grade: 'A', submittedAt: new Date().toISOString(), suspicious: false },
            { studentName: 'Bob Smith', score: 42, maxScore: 50, percentage: 84, grade: 'B', submittedAt: new Date().toISOString(), suspicious: true },
            { studentName: 'Carol Davis', score: 38, maxScore: 50, percentage: 76, grade: 'C', submittedAt: new Date().toISOString(), suspicious: false },
          ],
          questionStats: [
            { questionNumber: 1, averageScore: 4.8, maxScore: 5, difficulty: 'Easy' },
            { questionNumber: 2, averageScore: 3.2, maxScore: 5, difficulty: 'Medium' },
            { questionNumber: 3, averageScore: 2.5, maxScore: 5, difficulty: 'Hard' },
          ]
        }
        
        setReport(mockReport)
      } catch (error) {
        console.error('Error fetching report:', error)
      } finally {
        setLoading(false)
      }
    }
    
    fetchReport()
  }, [testId])

  const generatePDF = () => {
    if (!report) return

    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.setTextColor(56, 189, 248)
    doc.text('Class Performance Report', 105, 20, { align: 'center' })
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Test: ${report.testTitle}`, 20, 40)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50)
    
    // Summary stats
    autoTable(doc, {
      startY: 60,
      head: [['Metric', 'Value']],
      body: [
        ['Total Students', report.totalStudents.toString()],
        ['Average Score', `${report.averageScore.toFixed(1)}/${report.submissions[0]?.maxScore || 50}`],
        ['Highest Score', report.highestScore.toString()],
        ['Lowest Score', report.lowestScore.toString()],
        ['Class Average', `${((report.averageScore / (report.submissions[0]?.maxScore || 50)) * 100).toFixed(1)}%`]
      ],
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Student scores
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Student', 'Score', 'Percentage', 'Grade', 'Status']],
      body: report.submissions.map(s => [
        s.studentName,
        `${s.score}/${s.maxScore}`,
        `${s.percentage}%`,
        s.grade,
        s.suspicious ? '⚠ Review' : '✓ Normal'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
      bodyStyles: { minCellHeight: 10 },
    })
    
    // Question analysis
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Question', 'Average Score', 'Max Score', 'Difficulty']],
      body: report.questionStats.map(q => [
        `Q${q.questionNumber}`,
        q.averageScore.toFixed(1),
        q.maxScore.toString(),
        q.difficulty
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Grade distribution
    const gradeDistribution = report.submissions.reduce((acc, s) => {
      acc[s.grade] = (acc[s.grade] || 0) + 1
      return acc
    }, {} as Record<string, number>)
    
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Grade', 'Students', 'Percentage']],
      body: Object.entries(gradeDistribution).map(([grade, count]) => [
        grade,
        count.toString(),
        `${((count / report.totalStudents) * 100).toFixed(1)}%`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Footer
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pageCount} • Generated by OfflineTests • Confidential`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      )
    }
    
    doc.save(`Class_Report_${report.testTitle.replace(/\s+/g, '_')}.pdf`)
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-accent"></div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-red-400 mb-4">Report Not Found</h1>
          <button
            onClick={() => router.push('/')}
            className="px-6 py-2 bg-accent rounded-lg hover:bg-blue-500 transition-colors"
          >
            Return Home
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold text-white">Class Performance Report</h1>
              <p className="text-gray-400 mt-2">
                {report.testTitle} • {report.totalStudents} students
              </p>
            </div>
            <button
              onClick={generatePDF}
              className="px-6 py-3 bg-accent text-white font-semibold rounded-lg hover:bg-blue-500 transition-colors flex items-center space-x-2"
            >
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"/>
              </svg>
              <span>Export PDF</span>
            </button>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-8">
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-accent">{report.totalStudents}</div>
            <div className="text-sm text-gray-400 mt-1">Total Students</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-green-400">{report.averageScore.toFixed(1)}</div>
            <div className="text-sm text-gray-400 mt-1">Average Score</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-yellow-400">{report.highestScore}</div>
            <div className="text-sm text-gray-400 mt-1">Highest Score</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-red-400">{report.lowestScore}</div>
            <div className="text-sm text-gray-400 mt-1">Lowest Score</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-purple-400">
              {((report.averageScore / (report.submissions[0]?.maxScore || 50)) * 100).toFixed(1)}%
            </div>
            <div className="text-sm text-gray-400 mt-1">Class Average</div>
          </div>
        </div>

        {/* Student Scores Table */}
        <div className="bg-surface border border-border rounded-xl p-6 mb-8">
          <h3 className="text-xl font-semibold mb-6">Student Scores</h3>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-3 px-4 text-gray-400 font-medium">Student</th>
                  <th className="text-left py-3 px-4 text-gray-400 font-medium">Score</th>
                  <th className="text-left py-3 px-4 text-gray-400 font-medium">Percentage</th>
                  <th className="text-left py-3 px-4 text-gray-400 font-medium">Grade</th>
                  <th className="text-left py-3 px-4 text-gray-400 font-medium">Status</th>
                </tr>
              </thead>
              <tbody>
                {report.submissions.map((s, index) => (
                  <tr key={index} className="border-b border-border/50 hover:bg-background/50">
                    <td className="py-3 px-4">{s.studentName}</td>
                    <td className="py-3 px-4 font-mono">{s.score}/{s.maxScore}</td>
                    <td className="py-3 px-4">
                      <div className="flex items-center">
                        <span className="mr-2">{s.percentage}%</span>
                        <div className="w-16 h-2 bg-background rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-accent rounded-full"
                            style={{ width: `${s.percentage}%` }}
                          />
                        </div>
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <span className={`px-2 py-1 rounded text-xs ${
                        s.grade === 'A' ? 'bg-green-900/30 text-green-400' :
                        s.grade === 'B' ? 'bg-blue-900/30 text-blue-400' :
                        s.grade === 'C' ? 'bg-yellow-900/30 text-yellow-400' :
                        s.grade === 'D' ? 'bg-orange-900/30 text-orange-400' :
                        'bg-red-900/30 text-red-400'
                      }`}>
                        {s.grade}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      {s.suspicious ? (
                        <span className="text-yellow-400 flex items-center">
                          <span className="mr-1">⚠</span> Review
                        </span>
                      ) : (
                        <span className="text-green-400 flex items-center">
                          <span className="mr-1">✓</span> Normal
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Question Analysis */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="bg-surface border border-border rounded-xl p-6">
            <h3 className="text-xl font-semibold mb-6">Question Analysis</h3>
            <div className="space-y-4">
              {report.questionStats.map((q) => (
                <div key={q.questionNumber} className="bg-background border border-border rounded-lg p-4">
                  <div className="flex justify-between items-center mb-2">
                    <span className="font-medium">Question {q.questionNumber}</span>
                    <span className={`px-2 py-1 rounded text-xs ${
                      q.difficulty === 'Easy' ? 'bg-green-900/30 text-green-400' :
                      q.difficulty === 'Medium' ? 'bg-yellow-900/30 text-yellow-400' :
                      'bg-red-900/30 text-red-400'
                    }`}>
                      {q.difficulty}
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-400">Average Score:</span>
                    <span className="font-mono">{q.averageScore.toFixed(1)}/{q.maxScore}</span>
                  </div>
                  <div className="mt-2">
                    <div className="flex justify-between text-xs text-gray-400 mb-1">
                      <span>0</span>
                      <span>{q.maxScore}</span>
                    </div>
                    <div className="h-2 bg-background rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-accent rounded-full"
                        style={{ width: `${(q.averageScore / q.maxScore) * 100}%` }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Grade Distribution */}
          <div className="bg-surface border border-border rounded-xl p-6">
            <h3 className="text-xl font-semibold mb-6">Grade Distribution</h3>
            <div className="space-y-4">
              {['A', 'B', 'C', 'D', 'F'].map((grade) => {
                const count = report.submissions.filter(s => s.grade === grade).length
                const percentage = (count / report.submissions.length) * 100
                
                return (
                  <div key={grade} className="space-y-2">
                    <div className="flex justify-between items-center">
                      <span className="font-medium">Grade {grade}</span>
                      <span className="text-gray-400">{count} students ({percentage.toFixed(1)}%)</span>
                    </div>
                    <div className="h-3 bg-background rounded-full overflow-hidden">
                      <div 
                        className="h-full rounded-full"
                        style={{ 
                          width: `${percentage}%`,
                          backgroundColor: 
                            grade === 'A' ? '#10b981' :
                            grade === 'B' ? '#3b82f6' :
                            grade === 'C' ? '#f59e0b' :
                            grade === 'D' ? '#f97316' : '#ef4444'
                        }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
            
            {/* Stats Summary */}
            <div className="mt-8 pt-6 border-t border-border">
              <h4 className="font-semibold mb-4">Summary Statistics</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-sm text-gray-400">Median Score</div>
                  <div className="text-xl font-bold">42/50</div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">Standard Deviation</div>
                  <div className="text-xl font-bold">6.4</div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">Pass Rate (≥60%)</div>
                  <div className="text-xl font-bold text-green-400">92%</div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">Suspicious Activity</div>
                  <div className="text-xl font-bold text-yellow-400">
                    {report.submissions.filter(s => s.suspicious).length}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-400">
          <p>Report generated on {new Date().toLocaleDateString()} • Data is encrypted and automatically expires</p>
        </div>
      </div>
    </div>
  )
}