'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface StudentReport {
  studentName: string
  testTitle: string
  submissionDate: string
  totalScore: number
  maxScore: number
  percentage: number
  grade: string
  questions: Array<{
    question: string
    studentAnswer: string
    correctAnswer: string
    score: number
    maxScore: number
    feedback?: string
  }>
  teacherNotes?: string
}

export default function StudentReportPage() {
  const params = useParams()
  const router = useRouter()
  const submissionId = params.submissionId as string
  
  const [report, setReport] = useState<StudentReport | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Fetch report data
    const fetchReport = async () => {
      try {
        // Mock data - in production, fetch from API
        const mockReport: StudentReport = {
          studentName: 'John Doe',
          testTitle: 'Calculus Midterm',
          submissionDate: new Date().toISOString(),
          totalScore: 42,
          maxScore: 50,
          percentage: 84,
          grade: 'B',
          questions: [
            {
              question: 'What is the derivative of x²?',
              studentAnswer: '2x',
              correctAnswer: '2x',
              score: 5,
              maxScore: 5,
              feedback: 'Perfect!'
            },
            {
              question: 'Solve for x: 2x + 3 = 11',
              studentAnswer: 'x = 3',
              correctAnswer: 'x = 4',
              score: 2,
              maxScore: 5,
              feedback: 'Check your arithmetic: 2*3 + 3 = 9, not 11'
            },
            {
              question: 'What is ∫ x dx?',
              studentAnswer: 'x²/2 + C',
              correctAnswer: 'x²/2 + C',
              score: 5,
              maxScore: 5,
              feedback: 'Excellent work!'
            }
          ],
          teacherNotes: 'Good effort overall. Pay attention to basic algebra.'
        }
        
        setReport(mockReport)
      } catch (error) {
        console.error('Error fetching report:', error)
      } finally {
        setLoading(false)
      }
    }
    
    fetchReport()
  }, [submissionId])

  const generatePDF = () => {
    if (!report) return

    const doc = new jsPDF()
    
    // Title
    doc.setFontSize(20)
    doc.setTextColor(56, 189, 248) // Accent color
    doc.text('Test Report', 105, 20, { align: 'center' })
    
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`Student: ${report.studentName}`, 20, 40)
    doc.text(`Test: ${report.testTitle}`, 20, 50)
    doc.text(`Date: ${new Date(report.submissionDate).toLocaleDateString()}`, 20, 60)
    
    // Summary table
    autoTable(doc, {
      startY: 70,
      head: [['Metric', 'Value']],
      body: [
        ['Total Score', `${report.totalScore}/${report.maxScore}`],
        ['Percentage', `${report.percentage}%`],
        ['Grade', report.grade]
      ],
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Questions table
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Question', 'Your Answer', 'Correct Answer', 'Score', 'Feedback']],
      body: report.questions.map(q => [
        q.question.substring(0, 30) + '...',
        q.studentAnswer,
        q.correctAnswer,
        `${q.score}/${q.maxScore}`,
        q.feedback || ''
      ]),
      theme: 'grid',
      headStyles: { fillColor: [56, 189, 248] },
    })
    
    // Teacher notes
    if (report.teacherNotes) {
      doc.setFontSize(11)
      doc.text('Teacher Notes:', 20, (doc as any).lastAutoTable.finalY + 20)
      doc.setFontSize(10)
      const splitNotes = doc.splitTextToSize(report.teacherNotes, 170)
      doc.text(splitNotes, 20, (doc as any).lastAutoTable.finalY + 30)
    }
    
    // Footer
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(128, 128, 128)
      doc.text(
        `Page ${i} of ${pageCount} • Generated by OfflineTests`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      )
    }
    
    doc.save(`Test_Report_${report.studentName}.pdf`)
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-accent"></div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-red-400 mb-4">Report Not Found</h1>
          <button
            onClick={() => router.push('/')}
            className="px-6 py-2 bg-accent rounded-lg hover:bg-blue-500 transition-colors"
          >
            Return Home
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold text-white">Test Report</h1>
              <p className="text-gray-400 mt-2">
                Results for <span className="text-accent">{report.studentName}</span>
              </p>
            </div>
            <button
              onClick={generatePDF}
              className="px-6 py-3 bg-accent text-white font-semibold rounded-lg hover:bg-blue-500 transition-colors flex items-center space-x-2"
            >
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"/>
              </svg>
              <span>Download PDF</span>
            </button>
          </div>
        </div>

        {/* Summary Card */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-accent">{report.totalScore}/{report.maxScore}</div>
            <div className="text-sm text-gray-400 mt-1">Total Score</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-green-400">{report.percentage}%</div>
            <div className="text-sm text-gray-400 mt-1">Percentage</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-yellow-400">{report.grade}</div>
            <div className="text-sm text-gray-400 mt-1">Grade</div>
          </div>
          <div className="bg-surface border border-border rounded-xl p-6">
            <div className="text-3xl font-bold text-purple-400">{report.questions.length}</div>
            <div className="text-sm text-gray-400 mt-1">Questions</div>
          </div>
        </div>

        {/* Questions */}
        <div className="space-y-6 mb-8">
          <h2 className="text-xl font-semibold">Question Breakdown</h2>
          {report.questions.map((q, index) => (
            <div key={index} className="bg-surface border border-border rounded-xl p-6">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h3 className="font-semibold">Question {index + 1}</h3>
                  <div className="text-sm text-gray-400 mt-1">{q.question}</div>
                </div>
                <div className={`px-3 py-1 rounded-full ${
                  q.score === q.maxScore 
                    ? 'bg-green-900/30 text-green-400' 
                    : 'bg-yellow-900/30 text-yellow-400'
                }`}>
                  {q.score}/{q.maxScore}
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <div className="text-sm font-medium text-gray-400 mb-2">Your Answer</div>
                  <div className="bg-background border border-yellow-700/50 rounded-lg p-3">
                    <p className="text-yellow-300">{q.studentAnswer}</p>
                  </div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-400 mb-2">Correct Answer</div>
                  <div className="bg-background border border-green-700/50 rounded-lg p-3">
                    <p className="text-green-300">{q.correctAnswer}</p>
                  </div>
                </div>
              </div>
              
              {q.feedback && (
                <div>
                  <div className="text-sm font-medium text-gray-400 mb-2">Feedback</div>
                  <div className="bg-background border border-blue-700/50 rounded-lg p-3">
                    <p className="text-blue-300">{q.feedback}</p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Teacher Notes */}
        {report.teacherNotes && (
          <div className="bg-surface border border-border rounded-xl p-6">
            <h3 className="text-lg font-semibold mb-4">Teacher's Notes</h3>
            <div className="bg-background border border-border rounded-lg p-4">
              <p className="text-gray-300">{report.teacherNotes}</p>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-400">
          <p>Report generated on {new Date().toLocaleDateString()}</p>
          <p className="mt-1">This report is for personal review only. Scores are final.</p>
        </div>
      </div>
    </div>
  )
}